name: ProRNA3D-single
channels:
  - pytorch
  - esri
  - dglteam
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - brotlipy=0.7.0=py310h7f8727e_1002
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.6.15=ha878542_0
  - certifi=2022.6.15=pyhd8ed1ab_1
  - cffi=1.15.0=py310hd667e15_1
  - click=8.1.3=py310hff52083_0
  - cryptography=37.0.1=py310h9ce1e76_0
  - cudatoolkit=11.6.0=hecad31d_10
  - dgl=0.9.0=py310_0
  - dgl-cuda11.6=0.9.0=py310_0
  - docker-pycreds=0.4.0=py_0
  - einops=0.3.2=py_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.8.0=pyhd8ed1ab_0
  - freetype=2.10.4=h0708190_1
  - future=0.18.2=py310h06a4308_1
  - giflib=5.2.1=h36c2ea0_2
  - gitdb=4.0.9=pyhd8ed1ab_0
  - gitpython=3.1.27=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - idna=3.3=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jbig=2.1=h7f98852_2003
  - joblib=1.1.0=pyhd8ed1ab_0
  - jpeg=9e=h166bdaf_1
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=2.2.1=h9c3ff4c_0
  - libblas=3.9.0=12_linux64_mkl
  - libcblas=3.9.0=12_linux64_mkl
  - libdeflate=1.7=h7f98852_5
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.17=h166bdaf_0
  - libpng=1.6.37=h21135ba_2
  - libprotobuf=3.20.1=h4ff587b_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.3.0=hf544144_1
  - libuuid=1.0.3=h7f8727e_2
  - libwebp=1.2.2=h3452ae3_0
  - libwebp-base=1.2.2=h7f98852_1
  - lz4-c=1.9.3=h9c3ff4c_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py310h7f8727e_0
  - mkl_fft=1.3.1=py310hd6ae3a3_0
  - mkl_random=1.2.2=py310h00e6091_0
  - ncurses=6.3=h5eee18b_3
  - nettle=3.6=he412f7d_0
  - networkx=2.8.4=py310h06a4308_0
  - ninja=1.10.2=h06a4308_5
  - ninja-base=1.10.2=hd09550d_5
  - numpy=1.22.3=py310hfa59a62_0
  - numpy-base=1.22.3=py310h9585f30_0
  - openh264=2.1.1=h780b84a_0
  - openssl=1.1.1q=h7f8727e_0
  - packaging=21.3=pyhd8ed1ab_0
  - pathtools=0.1.2=py_1
  - pillow=9.2.0=py310hace64e9_1
  - pip=22.1.2=py310h06a4308_0
  - promise=2.3=py310hff52083_6
  - protobuf=3.20.1=py310hd8f1fbe_0
  - psutil=5.9.1=py310h5764c6d_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyopenssl=22.0.0=pyhd3eb1b0_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=py310h06a4308_0
  - python=3.10.4=h12debd9_0
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=1.12.0=py3.10_cuda11.6_cudnn8.3.2_0
  - pytorch-mutex=1.0=cuda
  - pyyaml=6.0=py310h5764c6d_4
  - readline=8.1.2=h7f8727e_1
  - requests=2.28.1=py310h06a4308_0
  - scikit-learn=1.1.1=py310hffb9edd_0
  - scipy=1.7.3=py310hfa59a62_0
  - sentry-sdk=1.9.5=pyhd8ed1ab_0
  - setproctitle=1.2.2=py310h5764c6d_2
  - setuptools=61.2.0=py310h06a4308_0
  - shortuuid=1.0.9=pyha770c72_1
  - six=1.16.0=pyhd3eb1b0_1
  - smmap=3.0.5=pyh44b312d_0
  - sqlite=3.38.5=hc218d9a_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.12=h1ccaba5_0
  - torchaudio=0.12.0=py310_cu116
  - torchvision=0.13.0=py310_cu116
  - tqdm=4.64.0=py310h06a4308_0
  - typing-extensions=4.1.1=hd3eb1b0_0
  - typing_extensions=4.1.1=pyh06a4308_0
  - tzdata=2022a=hda174b7_0
  - wandb=0.13.1=pyhd8ed1ab_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xz=5.2.5=h7f8727e_1
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.12=h7f8727e_2
  - zstd=1.5.0=ha95c52a_0
  - pip:
      - charset-normalizer==2.1.0
      - lie-learn==0.0.1.post1
      - urllib3==1.26.11
